apiVersion: v1
kind: Service
metadata:
  name: qandax-app-service
  namespace: default
spec:
  selector:
    app: qandax-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort